import Head from "next/head";
import { useRouter } from "next/router";
import React from "react";
import { getCookie } from "../utils/cookie";

export default function Home() {
  const router = useRouter();

  const token = getCookie("token");

  React.useEffect(() => {
    if (token) {
      router.push("/agent");
    }

    router.push("/auth/login");
  }, [router, token]);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
}
